# ERRORS #
class ValueDefError(Exception): ...
class ValueLoadError(Exception): ...
class MasterError(Exception): ...

# EXCEPTIONS
class ValueDefException(Exception): ...
class ValueLoadException(Exception): ...
class MasterException(Exception): ...
class criticalException(Exception): ...
class controlledExit(Exception): ...

#FAILURES
class ValueDefFailure(Exception): ...
class ValueLoadFailure(Exception): ...
class MasterFailure(Exception): ...

#REQUESTS
class ExitRequest(Exception): ...
class ShutdownRequest(Exception): ...
class DestroyRequest(Exception): ...
